export const ACTION_FETCHING        = 'ACTION_FETCHING';
export const ACTION_FETCH_OK        = 'ACTION_FETCH_OK';
export const ACTION_FETCH_ERROR     = 'ACTION_FETCH_ERROR';

export const INDEX_ACTION_INIT      = 'INDEX_ACTION_INIT';
export const INDEX_ACTION_LOADING   = 'INDEX_ACTION_LOADING';